{
 "title": "Application Status",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Error Logs / Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (service_name) (\r\n  count_over_time(\r\n    {service_name=~\"web|sidekiq|yolo-service|upscale-service\"} \r\n      | detected_level=\"error\"\r\n    [5m]\r\n  )\r\n)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"web|sidekiq|yolo-service|upscale-service\"} | detected_level=`error`"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemFree_bytes/node_memory_MemAvailable_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Status",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "avg_over_time(up{job=~\"yolo|rails|upscale|redis|mongodb\"}[5m]) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(increase(smart_collection_http_requests_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second (Method/Status)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "increase(smart_collection_http_requests_total[1h])",
     "legendFormat": "{{method}}-{{status}}"
    }
   ]
  }
 ]
}